### ISSUE TITLE
Is it compatible with the Google Translate extension? Or just a bug?

### ISSUE THREAD

**Issue by mykeehu** [SicariusSicariiStuff/Diffusion_TTS#1]
I use Google Translate extension to chat in my own language, Hungarian. I don't know if it's a bug or something else, but the following problems occurred.

I get this message back in the chat bubble when I regenerate a text:
`Empty reply, try regenerating`

However, I can see that it did generate something:
`Output generated in 30.17 seconds (1.39 tokens/s, 42 tokens, context 3558, seed 105217700)`

------------------------
I've also tried sending a message, which works for something. This is what I see in the command window (the response looks good):
```
Output generated in 7.29 seconds (7.68 tokens/s, 56 tokens, context 3558, seed 278145728)
Generating autoregressive samples..
Nos, úgy tűnik, nem is vetted a fáradságot, hogy várj.
0it [00:00, ?it/s]
Computing best candidates using CLVP
0it [00:00, ?it/s]
```

However, I got this error in the chat:
```
Traceback (most recent call last):

File "I:\oobabooga_windows\text-generation-webui\extensions\Diffusion_TTS\script.py", line 289, in output_modifier

generate_audio(model, voice_samples, conditioning_latents, output_dir, output_file, gen_kwargs, texts)
File "I:\oobabooga_windows\text-generation-webui\extensions\Diffusion_TTS\script.py", line 325, in generate_audio

gen = tts.tts_with_preset(text, voice_samples=samples, conditioning_latents=latents, **gen_kwargs)
File "I:\oobabooga_windows\text-generation-webui\extensions\Diffusion_TTS\tortoise\tortoise\api.py", line 353, in tts_with_preset

return self.tts(text, **settings)
File "I:\oobabooga_windows\text-generation-webui\extensions\Diffusion_TTS\tortoise\tortoise\api.py", line 497, in tts

clip_results = torch.cat(clip_results, dim=0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors
```

My settings is default:
![image](https://github.com/SicariusSicariiStuff/Diffusion_TTS/assets/6390413/41fc8fe9-5b4d-4f0d-9d99-334208143df0)

**Comment by SicariusSicariiStuff** [comment]
The model is trained only for the English language.
Regarding the error, try changing number of auto regressive samples to 16, I updated the extension to address similar errors. These settings work well for nvidia 1060m, but on A5000 it glitches in a similar way that you described if the number of samples is lower than 16.
