### ISSUE TITLE
Having difficulties installing it on Windows

### ISSUE THREAD

**Issue by guispfilho** [SicariusSicariiStuff/Diffusion_TTS#13]
Whe installing it on windows, if I follow the steps below, it will install the extension into into the folder that Miniconda starts, which is C:\Users\username>

```
conda create --name tortoise python=3.9 numba inflect
conda activate tortoise
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
conda install transformers=4.29.2
git clone https://github.com/neonbjb/tortoise-tts.git
cd tortoise-tts
python setup.py install
```

But my text-gen-webui is in D:\webui\text-generation-webui\extensions>, and it seems that "cd D:\webui\text-generation-webui\extensions" doesn't work. Is it possible (or even if  Ishould ) create the conda environment in the D:\webui\text-generation-webui\ folder? Or should I create it the startand folder that Minicond starts (C:\Users\username>), and them move to D:\webui\text-generation-webui\extensions 

Something like this?
```
conda create --name tortoise python=3.9 numba inflect
conda activate tortoise
cd D:\webui\text-generation-webui\extensions 
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
conda install transformers=4.29.2
git clone https://github.com/neonbjb/tortoise-tts.git
cd tortoise-tts
python setup.py install
```

And another thing, I couldn't find the file tts_preprocessor.py in my D:\webui\text-generation-webui\extensions folder. Or is it in the just created tortoise folder?

I think those are stupid questions, but I'm not really used to conda. Any help is appreciated.
Thank you for your time.

**Comment by SicariusSicariiStuff** [comment]
I don't use windows, however it seems you are creating a separate conda venv from the one booga creates. 
Regarding the tts_preprocessor.py, the script copies it to modules. Try asking around in booga's reddit, I know some windows users resolved similar issues. Please keep us updated regarding what was the issue and how u eventually resolved it, so it can help other windows users as well.

**Comment by guispfilho** [comment]
When installing text-gen-webui, it already creates a conda venv? If not, I should create a conda venv into D:\webui\text-generation-webui or D:\webui\text-generation-webui\extensions ?
