### ISSUE TITLE
AttributeError: module 'modules.chat' has no attribute 'save_persistent_history'

### ISSUE THREAD

**Issue by whmc76** [SicariusSicariiStuff/Diffusion_TTS#2]
Starting streaming server at ws://127.0.0.1:5005/api/v1/stream
Starting API at http://127.0.0.1:5000/api

Thanks for being a Gradio user! If you have questions or feedback, please join our Discord server and chat with us: https://discord.gg/feTf9x3ZSB
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Closing server running on port: 7860
2023-09-23 14:03:18 INFO:Loading the extension "gallery"...
2023-09-23 14:03:18 INFO:Loading the extension "Diffusion_TTS"...
Traceback (most recent call last):
  File "E:\oobabooga_windows\text-generation-webui\server.py", line 235, in <module>
    create_interface()
  File "E:\oobabooga_windows\text-generation-webui\server.py", line 138, in create_interface
    extensions_module.create_extensions_block()  # Extensions block
  File "E:\oobabooga_windows\text-generation-webui\modules\extensions.py", line 192, in create_extensions_block
    extension.ui()
  File "E:\oobabooga_windows\text-generation-webui\extensions\Diffusion_TTS\script.py", line 393, in ui
    chat.save_persistent_history, gradio('history', 'character_menu', 'mode'), None).then(
AttributeError: module 'modules.chat' has no attribute 'save_persistent_history'

**Comment by SicariusSicariiStuff** [comment]
please provide more details

**Comment by berniw** [comment]
I experienced yesterday the same, I did a fresh pull of the text-generation-webui and then followed the installation instructions. I think that something has changed in modules/chat.py of the text-generation-webui, see https://github.com/oobabooga/text-generation-webui/commit/00ab450c13df00e7ffd94a19faee58e47572b6e4. Seems like "save_persistent_history" got removed.

Update: Found also this: https://github.com/oobabooga/text-generation-webui/issues/4037

**Comment by SicariusSicariiStuff** [comment]
I see, from what it seems, the new commit from oobabooga that added different chat sessions (the button that let u load several different chat logs instead of a single chat session) broke the TTS extensions.

unfortunately I don't have much time to tinker with this stuff. 
You can either use an older oobabooga commit or you are welcomed to help patching this extension :)

**Comment by IIEleven11** [comment]
In script.py comment out lines 387- 403 for a work around
