### ISSUE TITLE
(Windows) RuntimeError: torch.cat(): expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by Simplegram** [SicariusSicariiStuff/Diffusion_TTS#6]
num_autoregression_samples is 1 until the point of error (api.py, line 497), causing clip_results to be empty. I need to manually set num_autoregression_samples (api.py, line 428) to at least 16 so the floor division is not 0. I thought it was because of the tuning settings, but changing tuning settings did not resolve the issue.

After tinkering for a little bit, removing ```settings.update(kwargs) # allow overriding of preset settings with kwargs``` at api.py resolves the issue, though you can't use kwargs as a result.

**Comment by SicariusSicariiStuff** [comment]
thank you for reporting, yes this is a known issue now, setting num_autoregression_samples to 16 solves the problem.
in case it get stuck and u cant start a new chat history after changing  num_autoregression_samples to 16, disable the extension and restart booga. then start a new chat and re enable it.
