### ISSUE TITLE
ImportError: cannot import name 'broadcat' from 'rotary_embedding_torch' 

### ISSUE THREAD

**Issue by luthis1124** [SicariusSicariiStuff/Diffusion_TTS#7]
On first run:

File "oobabooga/extensions/Diffusion_TTS/tortoise/tortoise/models/transformer.py", line 6, in <module>
    from rotary_embedding_torch import RotaryEmbedding, broadcat
ImportError: cannot import name 'broadcat' from 'rotary_embedding_torch' (oobabooga/installer_files/env/lib/python3.11/site-packages/rotary_embedding_torch/__init__.py)

**Comment by luthis1124** [comment]
I checked rotary-embedding-torch-0.5.1.tar.gz

There is no broadcat, only RotaryEmbedding

Needs different version?

**Comment by luthis1124** [comment]
Ah I see,  it's been removed from the latest version:

def broadcat(tensors, dim = -1):
    broadcasted_tensors = broadcast_tensors(*tensors)
    return torch.cat(broadcasted_tensors, dim = dim)
    
The last version this method was in was rotary-embedding-torch-0.4.0

**Comment by luthis1124** [comment]
Fixed by:

pip uninstall rotary_embedding_torch
pip install rotary_embedding_torch==0.4.0

Need to update requirements.txt to specify version:

rotary_embedding_torch==0.4.0

**Comment by andecy64** [comment]
Thanks @luthis1124 good eyes :+1:

**Comment by luthis1124** [comment]
Cheers!

closing, requirements.txt has been updated
